GET http://localhost:3000/experiences
###

POST http://localhost:3000/experiences

### Student Index
GET http://localhost:3000/students

### Student Create
POST http://localhost:3000/students
Content-Type: application/json

{
  "first_name": "Britney", 
  "last_name": "Foor",
  "email": "britney@gmail.com", 
  "phone_number": "123-456-1234",
  "bio": "bio",
  "linkedin_url": "linkedin_url",
  "twitter_handle": "twitter_handle",
  "website_url": "website_url",
  "resume_url": "resume_url",
  "github_url": "github_url",
  "photo": "photo_url",
  "password": "password"
}

### Student Show 
GET http://localhost:3000/students/1

### Student Update
PATCH http://localhost:3000/students/1 
Content-Type: application/json

{
  "first_name": "Britney", 
  "last_name": "Foor",
  "email": "britney@gmail.com", 
  "phone_number": "123-456-1234",
  "bio": "New Bio",
  "linkedin_url": "linkedin_url",
  "twitter_handle": "twitter_handle",
  "website_url": "website_url",
  "resume_url": "resume_url",
  "github_url": "github_url",
  "photo": "photo_url",
  "password": "password"
}